<?php
$_lang['degoyaPickResource.title'] = 'degoyaPickResource';
$_lang['degoyaPickResource.parentsTitle'] = 'Root';
$_lang['degoyaPickResource.parentsHelp'] = 'Select Root-Resource';
$_lang['degoyaPickResource.excludesTitle'] = 'Excludes';
$_lang['degoyaPickResource.excludesHelp'] = 'A list of IDs to exclude from treelist.';
$_lang['degoyaPickResource.expandedTitle'] = 'Expanded';
$_lang['degoyaPickResource.expandedHelp'] = 'expand all folders';
$_lang['degoyaPickResource.templatesTitle'] = 'Templates';
$_lang['degoyaPickResource.templatesHelp'] = 'List with Template IDs that should be shown.';
$_lang['degoyaPickResource.rootVisibleTitle'] = 'Root Visible';
$_lang['degoyaPickResource.rootVisibleHelp'] = 'Select if the Root should be visible';
$_lang['degoyaPickResource.publishedOnlyTitle'] = 'Published Only';
$_lang['degoyaPickResource.publishedOnlyHelp'] = 'show only published Resources in Tree';
$_lang['degoyaPickResource.contextTitle'] = 'Limit Context';
$_lang['degoyaPickResource.contextHelp'] = 'Limit to Resource Context';
$_lang['degoyaPickResource.contextParentsTitle'] = 'Context Root';
$_lang['degoyaPickResource.contextParentsHelp'] = 'Root Resource for each context when limited to resource context Format: context1==resourceid1||context2==resourceid2';
$_lang['degoyaPickResource.btnCaptionDelete'] = 'Delete selection';
$_lang['degoyaPickResource.btnCaptionChoose'] = 'Select Resource';
$_lang['degoyaPickResource.winTitle'] = 'Select Resource';
